# baseURL = 'https://jtalex.com/'
baseURL = 'https://mrstarman18.github.io/JustinTAlexander-AWebsite/'
languageCode = 'en-us'
title = "Justin T. Alexander: A Website"
theme = 'ananke'

[params.ananke.social]
[ananke.social.follow]
new_window_icon = true
networks = [ "instagram",
"twitter", "linkedin", "tiktok"]

[params.ananke.social.instagram]
username = "MrStarman18"

[params.ananke.social.twitter]
username = "MrStarman18"

[params.ananke.social.linkedin]
username = "Justin T. Alexander"

[params.ananke.social.tiktok]
username = "MrStarman18"
